"use client";
import { ToolFaq } from "@/components/ToolFaq";

import { useCallback, useRef, useState } from "react";
import { Spinner } from "@/components/Spinner";
import { encryptedPdfMessage } from "@/lib/pdf-errors";

type Locale = "en" | "zh";
type Card = { q: string; a: string };

const STR = {
  en: {
    title: "Make flashcards from a PDF",
    subtitle: "Upload a textbook chapter, lecture notes, or a manual and turn it into study flashcards — questions and answers drawn only from your document. Flip a card to check yourself.",
    drop: "Drag & drop a PDF here, or click to choose",
    choose: "Choose PDF", reading: "Reading…", count: "Cards", change: "Replace",
    generate: "Generate cards", generating: "Generating…", reset: "Start over",
    flip: "Tap to flip", question: "Q", answer: "A",
    noText: "No text found in this PDF. If it's a scan, run OCR first.",
    err: "Something went wrong: ",
    note: "Cards are generated by AI from your document. Give them a quick check before studying.",
  },
  zh: {
    title: "PDF 抽认卡",
    subtitle: "上传课本章节、讲义或手册，把它变成学习抽认卡——问题和答案只来自你的文档。点卡片翻面自测。",
    drop: "把 PDF 拖到这里，或点击选择",
    choose: "选择 PDF", reading: "读取中…", count: "卡片数", change: "替换",
    generate: "生成卡片", generating: "生成中…", reset: "重新开始",
    flip: "点击翻面", question: "问", answer: "答",
    noText: "这个 PDF 里没有文字。如果是扫描件，请先 OCR。",
    err: "出错了：",
    note: "卡片由 AI 从你的文档生成，学习前请快速核对。",
  },
};

export function QuizClient({ locale = "en" }: { locale?: Locale }) {
  const t = STR[locale] ?? STR.en;
  const [fileName, setFileName] = useState("");
  const [text, setText] = useState("");
  const [count, setCount] = useState(10);
  const [phase, setPhase] = useState<"idle" | "reading" | "ready" | "generating" | "done">("idle");
  const [cards, setCards] = useState<Card[]>([]);
  const [flipped, setFlipped] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const onFile = useCallback(async (file: File) => {
    if (!file || (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf"))) return;
    setError(null); setCards([]); setFlipped(new Set()); setFileName(file.name); setPhase("reading");
    try {
      const pdfjs = await import("pdfjs-dist");
      pdfjs.GlobalWorkerOptions.workerSrc = "/pdf.worker.min.mjs";
      const doc = await pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise;
      let out = "";
      for (let i = 1; i <= doc.numPages; i++) {
        const page = await doc.getPage(i);
        const content = await page.getTextContent();
        out += content.items.map((it) => ("str" in it ? it.str : "")).join(" ") + "\n";
      }
      try { doc.destroy(); } catch { /* ignore */ }
      const trimmed = out.replace(/[ \t]+/g, " ").replace(/\n{3,}/g, "\n\n").trim();
      if (!trimmed) { setError(t.noText); setPhase("idle"); return; }
      setText(trimmed); setPhase("ready");
    } catch (e) {
      setError(encryptedPdfMessage(e, locale) ?? (t.err + (e instanceof Error ? e.message : String(e)))); setPhase("idle");
    }
  }, [t, locale]);

  const generate = useCallback(async () => {
    if (!text) return;
    setPhase("generating"); setError(null); setCards([]); setFlipped(new Set());
    try {
      const res = await fetch("/api/quiz", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, count, locale }),
      });
      const data = await res.json();
      if (data?.ok && Array.isArray(data.cards) && data.cards.length > 0) {
        setCards(data.cards);
        setPhase("done");
      } else {
        setError(t.err + (data?.message || "Could not generate cards.")); setPhase("ready");
      }
    } catch (e) {
      setError(t.err + (e instanceof Error ? e.message : String(e))); setPhase("ready");
    }
  }, [text, count, locale, t]);

  const reset = () => { setFileName(""); setText(""); setCards([]); setFlipped(new Set()); setPhase("idle"); setError(null); };
  const toggle = (i: number) => setFlipped((p) => { const n = new Set(p); if (n.has(i)) n.delete(i); else n.add(i); return n; });

  return (
    <div className="mx-auto max-w-5xl px-5 pt-12 pb-16 sm:px-6 sm:pt-16 sm:pb-20">
      <h1 className="text-[30px] font-normal leading-[1.1] tracking-[-0.025em] text-[color:var(--foreground)] sm:text-[40px]">{t.title}</h1>
      <p className="mt-4 text-[16px] leading-[1.6] text-[color:var(--muted)]">{t.subtitle}</p>

      {phase === "idle" || phase === "reading" ? (
        <div
          className="mt-8 flex aspect-[16/9] w-full cursor-pointer flex-col items-center justify-center rounded-[var(--radius-xl)] border-2 border-dashed border-[color:var(--line)] bg-[color:var(--surface-subtle)] px-6 text-center transition hover:border-[color:var(--accent)] hover:bg-[color:var(--soft-accent)]"
          onClick={() => inputRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); e.currentTarget.classList.add("is-drag-over"); }}
          onDragLeave={(e) => { if (e.currentTarget === e.target) e.currentTarget.classList.remove("is-drag-over"); }}
          onDrop={(e) => { e.preventDefault(); const f = e.dataTransfer.files?.[0]; if (f) onFile(f); }}
        >
          {phase === "reading" ? (
            <div className="flex flex-col items-center justify-center gap-3 py-1"><Spinner /><p className="text-[14px] font-medium text-[color:var(--muted)]">{t.reading}</p></div>
          ) : (
            <button type="button" className="inline-flex h-12 w-1/2 items-center justify-center gap-2 rounded-[var(--radius)] bg-[color:var(--accent)] px-6 text-[15px] font-semibold text-white shadow-[0_4px_14px_rgba(62,207,142,0.32)] transition hover:opacity-90">{t.choose}</button>
          )}
          {phase !== "reading" && <p className="mt-4 text-sm text-[color:var(--muted)]">{locale === "zh" ? "或将文件拖放到此处" : "or drop your file here"}</p>}
          <input ref={inputRef} type="file" accept="application/pdf,.pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) onFile(f); }} />
        </div>
      ) : (
        <>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-3">
              <p className="truncate text-[14px] font-semibold text-[color:var(--foreground)]" title={fileName}>{fileName}</p>
              <button type="button" onClick={reset} className="text-[12.5px] font-medium text-[color:var(--muted)] hover:text-[color:var(--foreground)]">{t.change}</button>
            </div>
            <div className="flex shrink-0 items-center gap-3">
              <label className="flex items-center gap-2 text-[12.5px] text-[color:var(--muted)]">
                {t.count}
                <select value={count} onChange={(e) => setCount(+e.target.value)} className="h-9 rounded-[var(--radius)] border border-[color:var(--line)] bg-[color:var(--surface-subtle)] px-2 text-[13px] text-[color:var(--foreground)]">
                  {[5, 10, 15, 20].map((n) => <option key={n} value={n}>{n}</option>)}
                </select>
              </label>
              <button type="button" onClick={generate} disabled={phase === "generating"} className="inline-flex items-center gap-2 rounded-[var(--radius)] bg-[color:var(--accent)] px-5 py-2 text-[13px] font-semibold text-white transition hover:opacity-90 disabled:opacity-50">{phase === "generating" ? (<><Spinner /> {t.generating}</>) : t.generate}</button>
            </div>
          </div>

          {phase === "done" && cards.length > 0 && (
            <>
              <p className="mt-4 text-[12px] text-[color:var(--faint)]">{t.note}</p>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                {cards.map((c, i) => {
                  const open = flipped.has(i);
                  return (
                    <button key={i} type="button" onClick={() => toggle(i)} className="group flex min-h-[120px] flex-col rounded-[var(--radius-lg)] border border-[color:var(--line)] bg-[color:var(--surface)] p-4 text-left transition hover:border-[color:var(--accent)]">
                      <span className="text-[10px] font-bold uppercase tracking-[0.16em] text-[color:var(--accent-strong)]">{open ? t.answer : t.question}</span>
                      <span className="mt-2 flex-1 text-[14px] leading-6 text-[color:var(--foreground)]">{open ? c.a : c.q}</span>
                      <span className="mt-2 text-[11px] text-[color:var(--faint)] opacity-0 transition group-hover:opacity-100">{t.flip}</span>
                    </button>
                  );
                })}
              </div>
            </>
          )}
        </>
      )}

      {error && <div className="mt-4 rounded-[var(--radius)] border border-[rgba(248,113,113,0.3)] bg-[rgba(248,113,113,0.08)] px-4 py-3 text-[13.5px] text-[#f87171]">{error}</div>}
      <ToolFaq tool="flashcards" locale={locale} />
    </div>
  );
}
