import { defaultLocale, isLocale, type Locale } from "@/lib/i18n";

export type RuntimeLocale = Locale;

export function localeFromPathname(pathname: string | null | undefined): RuntimeLocale {
  const first = (pathname ?? "/").split("/").filter(Boolean)[0];
  return isLocale(first) ? first : defaultLocale;
}

export const runtimeCopy = {
  en: {
    shell: {
      header: {
        aria: "DockDocs navigation",
        homeAria: "DockDocs home",
        tagline: "AI Document Platform",
      },
      nav: [
        { name: "AI", href: "/#ai" },
        { name: "Convert", href: "/pdf-to-word", slug: "pdf-to-word" },
        { name: "Optimize", href: "/compress-pdf", slug: "compress-pdf" },
        { name: "Dashboard", href: "/dashboard", slug: "dashboard" },
        { name: "My Chats", href: "/my-chats" },
      ],
      brand: {
        aria: "Brand navigation",
        products: [
          {
            name: "DockDocs",
            href: "https://dockdocs.app",
            description: "AI document workspace for files, summaries, conversion, and review.",
          },
          {
            name: "DockIMG",
            href: "https://dockimg.app",
            description: "AI image workspace for visual editing, cleanup, and conversion.",
          },
          {
            name: "DockSEO",
            href: "https://dockseo.app",
            description: "Search workspace for snippets, metadata, and content checks.",
          },
          {
            name: "DockText",
            href: "https://docktext.app",
            description: "AI writing workspace for cleanup, summaries, and formatting.",
          },
        ],
      },
      footer: {
        aria: "Footer navigation",
        copyrightPrefix: "(c)",
        links: [
          { name: "Related Workspaces", href: "/#related-tools" },
          { name: "DockDocs", href: "/" },
          { name: "Privacy Policy", href: "/privacy-policy" },
          { name: "Terms", href: "/terms" },
          { name: "Sitemap", href: "/sitemap" },
        ],
      },
      relatedTools: {
        title: "Related Workspaces",
        description:
          "Move between the Dock products with one consistent workspace pattern across desktop and mobile.",
      },
      account: {
        account: "Account",
        myChats: "My Chats",
        signedIn: "Signed in",
        logout: "Logout",
        continueGoogle: "Continue with Google",
        email: "Email",
        password: "Password",
        login: "Login",
        actionFailed: "Account action failed.",
      },
      toolTemplate: {
        eyebrow: "AI Document Platform",
        schemaSlogan: "AI document platform for real file workflows",
      },
      legal: {
        privacy: "Privacy Policy",
        terms: "Terms",
        sitemap: "Sitemap",
      },
      trust: {
        localFirst: "Local-first",
        exportReady: "Export-ready",
      },
      metadata: {
        title: "DockDocs AI Document Workspace",
        description: "AI document tools for PDFs, office files, writing cleanup, and document workflows.",
      },
    },
    common: {
      upload: {
        label: "Upload",
        dragDrop: "Drag & drop document",
        selectedDescription: "File is selected and ready for the next runtime step.",
        supported: "Supported",
        limit: "Limit",
        processing: "Processing",
        successMessage: "Runtime UI state is ready and output is available below.",
        states: {
          empty: "Waiting for file",
          idle: "Ready for upload",
          selected: "File selected",
          processing: "Processing document",
          success: "Document ready",
          error: "Needs attention",
        },
      },
      result: {
        states: {
          empty: "No result",
          processing: "Generating",
          success: "Ready",
          error: "Error",
        },
        resultUnavailable: "Result unavailable",
        waitingForOutput: "Waiting for output",
        runtimeError: "The runtime returned an error state.",
        processingMessage:
          "The runtime is processing this document. Output will appear here when ready.",
        keyPoints: "Key points",
        nextActions: "Next actions",
        copy: "Copy",
        download: "Download",
        startChat: "Start chat",
      },
      errors: {
        unsupportedFile: "Unsupported file type. Supported formats:",
        fileTooLarge: "File is larger than the 25 MB UI limit.",
      },
    },
    chat: {
      heroEyebrow: "Chat with PDF MVP",
      heroTitle: "Ask grounded questions about a PDF.",
      heroDescription:
        "Upload a text-based PDF, review the extracted source status, and ask focused questions inside a document-first AI workspace.",
      primaryCta: "Open chat",
      secondaryCta: "Compress PDF",
      metrics: [
        { value: "12", label: "Page cap" },
        { value: "40k", label: "Text cap" },
        { value: "Live", label: "AI call" },
      ],
      workspaceLabel: "DockDocs Workspace",
      workspaceTitle: "Chat with PDF",
      mvp: "MVP",
      document: "Document",
      choosePdf: "Choose PDF",
      uploadHelp: "Text is extracted locally before a provider request is made.",
      documentStatus: "Document status",
      untitled: "Untitled document",
      initialStatus: "Upload a PDF to start.",
      pdfRequiredStatus: "PDF required.",
      pdfRequiredError: "Please choose a PDF file.",
      fileLimitStatus: "File size limit exceeded.",
      fileLimitError: "Please choose a PDF up to 25 MB.",
      readingStatus: "Reading PDF text in your browser.",
      noTextStatus: "No selectable text found.",
      noTextError: "This PDF does not expose readable text. OCR is required before chat can run.",
      extractionFailedStatus: "PDF text extraction failed.",
      extractionFailedError: "Unable to read this PDF.",
      readyStatus: "Ready: extracted {characters} characters from {pages} page{plural}.",
      sourceWaiting: "Waiting for source text",
      sourceReady: "{characters} characters ready",
      checks: ["Selectable text extracted", "Provider reference received", "Result generated"],
      collectionsLabel: "Collections",
      collections: [
        { name: "Board materials", count: "4 docs" },
        { name: "Contracts", count: "9 docs" },
        { name: "Research notes", count: "6 docs" },
      ],
      historyLabel: "Conversation history",
      defaultHistory: ["Review renewal risks", "Extract follow-up actions", "Compare policy clauses"],
      aiChat: "AI Chat",
      conversationTitle: "Ask a question about the PDF",
      conversationDescription:
        "A grounded AI workspace for document questions, summaries, references, and next actions.",
      messages: "Messages",
      runtime: "Runtime",
      asking: "Asking",
      starterTitle: "Start from a grounded question",
      starterDescription:
        "Upload a PDF with selectable text, then ask for facts, dates, clauses, risks, or action items grounded in the file.",
      suggestedQuestions: [
        "Summarize the main decision points",
        "What risks or blockers are mentioned?",
        "List dates, owners, and action items",
      ],
      knowledgeCards: [
        {
          title: "Summary",
          description: "Generate an executive brief from extracted document text.",
          prompt: "Create an executive summary of this PDF.",
        },
        {
          title: "Risks",
          description: "Surface unclear clauses, blockers, obligations, and dates.",
          prompt: "Identify risks, blockers, and obligations in this PDF.",
        },
        {
          title: "Actions",
          description: "Convert document content into owners, deadlines, and next steps.",
          prompt: "List action items, owners, and dates from this PDF.",
        },
      ],
      you: "You",
      assistant: "DockDocs",
      questionLabel: "Question",
      placeholder: "Ask about this PDF",
      ask: "Ask",
      sourceReferences: "Source references",
      documentText: "Document text",
      notExtracted: "Not extracted",
      pageContext: "Page context",
      firstPages: "First {pages} pages",
      pageIndexed: "{pages} page{plural} indexed",
      references: "References",
      citationCount: "{count} citation{plural}",
      providerResponseReceived: "Provider response received",
      providerCitations: "Provider citations when available",
      provider: "Provider",
      waitingForAi: "Waiting for AI response",
      knowledgeCardsLabel: "Knowledge cards",
      suggestedActions: "Suggested actions",
      sideActions: ["Summarize", "Find risks", "Create actions"],
      groundedTitle: "Grounded answers only",
      groundedDescription:
        "The chat request uses extracted document text as context. If the PDF does not contain the answer, the provider should say so.",
      providerFailed: "Chat provider request failed.",
      providerEmpty: "Chat provider returned no answer.",
      providerUnavailable: "Chat provider endpoint is unavailable.",
      unableToAnswer: "Unable to answer:",
      faqTitle: "Chat with PDF questions",
      faqs: [
        {
          question: "What is DockDocs Chat with PDF?",
          answer:
            "DockDocs Chat with PDF lets users upload a PDF, extract readable text in the browser, and ask questions through a configured AI provider.",
        },
        {
          question: "Does it answer without an AI provider?",
          answer:
            "No. If the provider endpoint or API key is unavailable, the page returns a real error instead of a simulated answer.",
        },
        {
          question: "Does it support scanned PDFs?",
          answer:
            "This MVP reads selectable PDF text. Scanned PDFs require OCR before chat can answer against their content.",
        },
        {
          question: "Is it static export compatible?",
          answer:
            "Yes. The page is static-export compatible, while provider calls are routed through a Netlify Function when deployed.",
        },
      ],
    },
    summary: {
      eyebrow: "AI",
      title: "Summarize documents into decisions and next actions.",
      description:
        "Turn long PDFs and office files into a reviewable AI output: summary, key points, entities, and suggested next steps.",
      primaryCta: "Upload document",
      secondaryCta: "Start chat",
      uploadTitle: "Upload for AI Summary",
      uploadDescription:
        "Drop a document here to prepare an AI summary workflow with visible limits and status states.",
      formats: "PDF, DOC, DOCX",
      limit: "Up to 25 MB",
      cta: "Select document",
      outputEyebrow: "Result",
      outputHeading: "Summary output that invites review and follow-up.",
      outputDescription:
        "The result view prioritizes readable AI output over a simple success state, keeping the next workflow one click away.",
      runtimeUploadTitle: "Runtime-bound summary upload",
      runtimeUploadDescription:
        "Select a document to verify summary empty, selected, processing, success, and error UI states.",
      resultEyebrow: "AI Summary",
      resultTitle: "Board report summary",
      resultSummary:
        "Revenue increased in the latest quarter, but customer support volume and vendor renewal risk need follow-up before the next operating review.",
      keyPoints: [
        "Support volume increased across enterprise accounts.",
        "Two vendor renewals need owner confirmation.",
        "Budget decisions are blocked by missing finance inputs.",
      ],
      actions: ["Copy summary", "Download brief", "Ask follow-up questions"],
      emptyMessage: "Select a document to generate a summary preview.",
    },
    ocr: {
      eyebrow: "AI",
      title: "Make scanned documents searchable and AI-ready.",
      description:
        "Prepare scanned PDFs for downstream AI workflows with a clean OCR upload, processing, and output interface.",
      uploadTitle: "Upload scanned PDF",
      uploadDescription:
        "Drop a scan or PDF here to prepare OCR extraction. The UI shows supported files, limits, and processing state.",
      formats: "PDF, PNG, JPG",
      limit: "Up to 25 MB",
      cta: "Select scan",
      outputEyebrow: "Output",
      outputHeading: "OCR output belongs in the workspace, not in a hidden file.",
      outputDescription:
        "Text extraction, confidence, and next AI actions are shown together so users understand what is ready.",
      runtimeUploadTitle: "Runtime-bound OCR upload",
      runtimeUploadDescription:
        "Select a scanned PDF or image to verify OCR upload, processing, output, and error UI states.",
      resultEyebrow: "OCR Text",
      resultTitle: "Extracted text preview",
      resultSummary:
        "The document is ready for review. Low-confidence sections are called out before summary or chat workflows continue.",
      keyPoints: [
        "Selectable text extracted from scanned pages.",
        "Low-confidence areas stay visible for review.",
        "Output can continue into Chat with PDF or AI Summary.",
      ],
      actions: ["Copy extracted text", "Download text file", "Summarize document"],
      emptyMessage: "Select a scanned document to generate OCR output.",
    },
    compress: {
      eyebrow: "Optimize",
      title: "Compress PDFs without leaving the document workspace.",
      description:
        "Reduce file size for email, portals, and office handoff while keeping the next document action visible.",
      primaryCta: "Upload PDF",
      secondaryCta: "Chat with PDF",
      uploadTitle: "Upload PDF to compress",
      uploadDescription:
        "Drop a PDF here or select a file from your device. The UI keeps limits, status, and output expectations visible.",
      formats: "PDF",
      limit: "Up to 25 MB",
      cta: "Select PDF",
      outputEyebrow: "Output",
      outputHeading: "Compression results should be reviewable, not just downloadable.",
      outputDescription:
        "The result area sets up a consistent DockDocs pattern for file savings, quality checks, and next-step AI document actions.",
      runtimeUploadTitle: "Runtime-bound compression upload",
      runtimeUploadDescription:
        "Select a PDF to verify upload, selected, processing, success, and error UI states without changing compression runtime logic.",
      resultEyebrow: "Compressed PDF",
      resultTitle: "Ready for office handoff",
      resultSummary:
        "The UI is bound to the selected file state and shows compression output only after the local runtime state reaches success.",
      keyPoints: [
        "File is smaller and ready for upload portals.",
        "Document readability remains the primary quality signal.",
        "Follow-up AI actions stay close to the result.",
      ],
      actions: ["Download compressed PDF", "Send to Chat with PDF", "Run AI Summary next"],
      emptyMessage: "Select a PDF to generate a compression result preview.",
      faqTitle: "PDF compression questions",
      faqs: [
        {
          question: "What is DockDocs Compress PDF?",
          answer:
            "DockDocs Compress PDF reduces file size as part of a broader AI document platform workflow.",
        },
        {
          question: "What files are supported?",
          answer:
            "This UI is focused on PDF upload and PDF output, with clear limits and processing states.",
        },
        {
          question: "Can I continue after compression?",
          answer:
            "Yes. The result surface points users toward download, copy, and follow-up document workflows.",
        },
        {
          question: "Does it work on mobile?",
          answer:
            "Yes. The upload area, limits, and output preview stack into a single-column mobile layout.",
        },
      ],
    },
    pdfToWord: {
      eyebrow: "Convert",
      title: "Convert PDFs into editable Word-ready documents.",
      description:
        "Keep conversion inside the same AI document platform, with upload limits, output status, and next actions in one place.",
      uploadTitle: "Upload PDF to convert",
      uploadDescription:
        "Drop a PDF here to prepare a Word conversion workflow without changing the backend provider logic.",
      formats: "PDF",
      limit: "Up to 25 MB",
      cta: "Select PDF",
      outputEyebrow: "Output",
      outputHeading: "Conversion output should explain what happened.",
      outputDescription:
        "The UI sets expectations around editable content, layout review, and follow-up document actions.",
      runtimeUploadTitle: "Runtime-bound conversion upload",
      runtimeUploadDescription:
        "Select a PDF to verify conversion upload, processing, success, and error UI states without changing provider logic.",
      resultEyebrow: "Word Output",
      resultTitle: "Editable document ready",
      resultSummary:
        "The converted document is ready for review, with layout notes and follow-up actions surfaced next to the result.",
      keyPoints: [
        "Text content is prepared for editing.",
        "Layout review remains visible before handoff.",
        "Users can continue with summary or chat workflows.",
      ],
      actions: ["Download DOCX", "Review layout notes", "Run AI Summary"],
      emptyMessage: "Select a PDF to generate a Word output preview.",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Document workspace overview.",
      description: "A SaaS-style home for recent files, AI activity, and next document actions.",
      newDocument: "New document",
      workspace: "Workspace",
      nav: ["Documents", "AI", "Convert", "Optimize", "Settings"],
      stats: [
        { label: "Documents", value: "18" },
        { label: "AI runs", value: "42" },
        { label: "Exports", value: "11" },
      ],
      recentLabel: "Recent documents",
      continueWork: "Continue work",
      openChat: "Open AI chat",
      documents: [
        { name: "Board-report.pdf", status: "Ready", action: "AI Summary" },
        { name: "Vendor-contract.pdf", status: "Review", action: "Chat" },
        { name: "Scanned-invoice.pdf", status: "Processing", action: "OCR" },
      ],
    },
  },
  zh: {
    shell: {
      header: {
        aria: "DockDocs 导航",
        homeAria: "DockDocs 首页",
        tagline: "AI 文档平台",
      },
      nav: [
        { name: "AI", href: "/zh/#tools" },
        { name: "转换", href: "/pdf-to-word", slug: "pdf-to-word" },
        { name: "优化", href: "/compress-pdf", slug: "compress-pdf" },
        { name: "控制台", href: "/dashboard", slug: "dashboard" },
        { name: "我的对话", href: "/my-chats" },
      ],
      brand: {
        aria: "品牌导航",
        products: [
          {
            name: "DockDocs",
            href: "https://dockdocs.app",
            description: "面向文件、摘要、转换和审阅的 AI 文档工作区。",
          },
          {
            name: "DockIMG",
            href: "https://dockimg.app",
            description: "面向视觉编辑、清理和转换的 AI 图像工作区。",
          },
          {
            name: "DockSEO",
            href: "https://dockseo.app",
            description: "面向摘要片段、元信息和内容检查的搜索工作区。",
          },
          {
            name: "DockText",
            href: "https://docktext.app",
            description: "面向文本清理、摘要和格式化的 AI 写作工作区。",
          },
        ],
      },
      footer: {
        aria: "页脚导航",
        copyrightPrefix: "(c)",
        links: [
          { name: "相关工作区", href: "/zh/#related-tools" },
          { name: "DockDocs", href: "/zh/" },
          { name: "隐私政策", href: "/zh/privacy-policy/" },
          { name: "服务条款", href: "/zh/terms/" },
          { name: "站点地图", href: "/zh/sitemap/" },
        ],
      },
      relatedTools: {
        title: "相关工作区",
        description: "在 Dock 产品之间切换，并保持一致的桌面与移动端工作区体验。",
      },
      account: {
        account: "账户",
        myChats: "我的对话",
        signedIn: "已登录",
        logout: "退出",
        continueGoogle: "使用 Google 继续",
        email: "邮箱",
        password: "密码",
        login: "登录",
        actionFailed: "账户操作失败。",
      },
      toolTemplate: {
        eyebrow: "AI 文档平台",
        schemaSlogan: "面向真实文件工作流的 AI 文档平台",
      },
      legal: {
        privacy: "隐私政策",
        terms: "服务条款",
        sitemap: "站点地图",
      },
      trust: {
        localFirst: "本地优先",
        exportReady: "可导出",
      },
      metadata: {
        title: "DockDocs AI 文档工作区",
        description: "面向 PDF、办公文件、文字清理和文档工作流的 AI 文档工具。",
      },
    },
    common: {
      upload: {
        label: "上传",
        dragDrop: "拖放文档",
        selectedDescription: "文件已选择，可以进入下一步处理。",
        supported: "支持格式",
        limit: "限制",
        processing: "处理中",
        successMessage: "运行状态已就绪，下方可以查看输出结果。",
        states: {
          empty: "等待文件",
          idle: "可上传",
          selected: "已选择文件",
          processing: "正在处理文档",
          success: "文档已就绪",
          error: "需要处理",
        },
      },
      result: {
        states: {
          empty: "暂无结果",
          processing: "生成中",
          success: "已就绪",
          error: "错误",
        },
        resultUnavailable: "结果不可用",
        waitingForOutput: "等待输出",
        runtimeError: "运行状态返回错误。",
        processingMessage: "文档正在处理中，完成后结果会显示在这里。",
        keyPoints: "关键要点",
        nextActions: "下一步操作",
        copy: "复制",
        download: "下载",
        startChat: "开始对话",
      },
      errors: {
        unsupportedFile: "不支持的文件类型。支持格式：",
        fileTooLarge: "文件超过 25 MB 界面限制。",
      },
    },
    chat: {
      heroEyebrow: "PDF 对话 MVP",
      heroTitle: "围绕 PDF 提出有来源的问题。",
      heroDescription:
        "上传可选择文字的 PDF，查看来源提取状态，并在文档优先的 AI 工作区中提出聚焦问题。",
      primaryCta: "打开对话",
      secondaryCta: "压缩 PDF",
      metrics: [
        { value: "12", label: "页数上限" },
        { value: "40k", label: "文字上限" },
        { value: "实时", label: "AI 调用" },
      ],
      workspaceLabel: "DockDocs 工作区",
      workspaceTitle: "PDF 对话",
      mvp: "MVP",
      document: "文档",
      choosePdf: "选择 PDF",
      uploadHelp: "文字会先在浏览器本地提取，然后再请求 AI provider。",
      documentStatus: "文档状态",
      untitled: "未命名文档",
      initialStatus: "上传 PDF 后开始。",
      pdfRequiredStatus: "需要 PDF 文件。",
      pdfRequiredError: "请选择 PDF 文件。",
      fileLimitStatus: "文件超过大小限制。",
      fileLimitError: "请选择 25 MB 以内的 PDF。",
      readingStatus: "正在浏览器中读取 PDF 文字。",
      noTextStatus: "没有找到可选择文字。",
      noTextError: "该 PDF 没有暴露可读取文字。需要先进行 OCR，再使用对话功能。",
      extractionFailedStatus: "PDF 文字提取失败。",
      extractionFailedError: "无法读取该 PDF。",
      readyStatus: "已就绪：从 {pages} 页中提取 {characters} 个字符。",
      sourceWaiting: "等待来源文字",
      sourceReady: "{characters} 个字符已就绪",
      checks: ["已提取可选择文字", "已收到 provider 引用", "已生成结果"],
      collectionsLabel: "文档集合",
      collections: [
        { name: "董事会材料", count: "4 个文档" },
        { name: "合同", count: "9 个文档" },
        { name: "研究笔记", count: "6 个文档" },
      ],
      historyLabel: "对话历史",
      defaultHistory: ["复核续约风险", "提取后续行动", "比较政策条款"],
      aiChat: "AI 对话",
      conversationTitle: "向 PDF 提问",
      conversationDescription: "用于文档问题、摘要、来源引用和下一步行动的可信 AI 工作区。",
      messages: "消息",
      runtime: "运行状态",
      asking: "提问中",
      starterTitle: "从有来源的问题开始",
      starterDescription:
        "上传包含可选择文字的 PDF，然后围绕事实、日期、条款、风险或行动项提问。",
      suggestedQuestions: ["总结主要决策点", "文中提到了哪些风险或阻碍？", "列出日期、负责人和行动项"],
      knowledgeCards: [
        {
          title: "摘要",
          description: "根据提取的文档文字生成管理层简报。",
          prompt: "请为这个 PDF 生成管理层摘要。",
        },
        {
          title: "风险",
          description: "找出不清楚的条款、阻碍、义务和日期。",
          prompt: "请识别这个 PDF 中的风险、阻碍和义务。",
        },
        {
          title: "行动",
          description: "将文档内容转为负责人、截止日期和下一步。",
          prompt: "请列出这个 PDF 中的行动项、负责人和日期。",
        },
      ],
      you: "你",
      assistant: "DockDocs",
      questionLabel: "问题",
      placeholder: "询问这个 PDF",
      ask: "提问",
      sourceReferences: "来源引用",
      documentText: "文档文字",
      notExtracted: "未提取",
      pageContext: "页面上下文",
      firstPages: "前 {pages} 页",
      pageIndexed: "已索引 {pages} 页",
      references: "引用",
      citationCount: "{count} 条引用",
      providerResponseReceived: "已收到 provider 响应",
      providerCitations: "可用时显示 provider 引用",
      provider: "Provider",
      waitingForAi: "等待 AI 响应",
      knowledgeCardsLabel: "知识卡片",
      suggestedActions: "建议操作",
      sideActions: ["生成摘要", "查找风险", "创建行动项"],
      groundedTitle: "只给出有来源的回答",
      groundedDescription: "对话请求会使用提取的文档文字作为上下文。如果 PDF 中没有答案，provider 应说明无法确认。",
      providerFailed: "Chat provider 请求失败。",
      providerEmpty: "Chat provider 未返回答案。",
      providerUnavailable: "Chat provider endpoint 不可用。",
      unableToAnswer: "无法回答：",
      faqTitle: "PDF 对话常见问题",
      faqs: [
        {
          question: "DockDocs PDF 对话是什么？",
          answer: "用户可以上传 PDF，在浏览器中提取可读取文字，并通过已配置的 AI provider 提问。",
        },
        {
          question: "没有 AI provider 可以回答吗？",
          answer: "不可以。如果 provider endpoint 或 API key 不可用，页面会返回真实错误，而不是模拟答案。",
        },
        {
          question: "支持扫描 PDF 吗？",
          answer: "当前 MVP 读取可选择的 PDF 文字。扫描 PDF 需要先 OCR，之后才能围绕内容提问。",
        },
        {
          question: "兼容静态导出吗？",
          answer: "兼容。页面可以静态导出，部署后 provider 调用通过 Netlify Function 处理。",
        },
      ],
    },
    summary: {
      eyebrow: "AI",
      title: "将文档总结为决策和下一步行动。",
      description: "把较长的 PDF 和办公文件转成可审阅的 AI 输出：摘要、关键点、实体和建议行动。",
      primaryCta: "上传文档",
      secondaryCta: "开始对话",
      uploadTitle: "上传以生成 AI 摘要",
      uploadDescription: "拖放文档，准备 AI 摘要工作流，并保持限制和状态可见。",
      formats: "PDF、DOC、DOCX",
      limit: "最高 25 MB",
      cta: "选择文档",
      outputEyebrow: "结果",
      outputHeading: "摘要结果应便于审阅和继续追问。",
      outputDescription: "结果区域优先展示可读的 AI 输出，而不是只显示成功状态，并保留下一步入口。",
      runtimeUploadTitle: "已绑定运行状态的摘要上传",
      runtimeUploadDescription: "选择文档以验证摘要的空、已选择、处理、成功和错误状态。",
      resultEyebrow: "AI 摘要",
      resultTitle: "董事会报告摘要",
      resultSummary: "最新季度收入增长，但客服量和供应商续约风险需要在下一次经营复盘前跟进。",
      keyPoints: ["企业客户支持量增加。", "两个供应商续约需要确认负责人。", "预算决策受缺失的财务输入阻塞。"],
      actions: ["复制摘要", "下载简报", "继续追问"],
      emptyMessage: "请选择文档以生成摘要预览。",
    },
    ocr: {
      eyebrow: "AI",
      title: "让扫描文档可搜索，并可进入 AI 工作流。",
      description: "用清晰的 OCR 上传、处理和输出界面，为后续 AI 工作流准备扫描 PDF。",
      uploadTitle: "上传扫描 PDF",
      uploadDescription: "拖放扫描件或 PDF，准备 OCR 提取。界面会显示支持格式、限制和处理状态。",
      formats: "PDF、PNG、JPG",
      limit: "最高 25 MB",
      cta: "选择扫描件",
      outputEyebrow: "输出",
      outputHeading: "OCR 输出应留在工作区中，而不是隐藏在文件里。",
      outputDescription: "文字提取、置信度和下一步 AI 操作一起展示，让用户知道哪些内容已就绪。",
      runtimeUploadTitle: "已绑定运行状态的 OCR 上传",
      runtimeUploadDescription: "选择扫描 PDF 或图片以验证 OCR 上传、处理、输出和错误状态。",
      resultEyebrow: "OCR 文字",
      resultTitle: "提取文字预览",
      resultSummary: "文档已可审阅。低置信度部分会在继续摘要或对话前显示。",
      keyPoints: ["已从扫描页面提取可用文字。", "低置信度区域保持可见，便于复核。", "输出可以继续进入 PDF 对话或 AI 摘要。"],
      actions: ["复制提取文字", "下载文本文件", "总结文档"],
      emptyMessage: "请选择扫描文档以生成 OCR 输出。",
    },
    compress: {
      eyebrow: "优化",
      title: "在文档工作区中完成 PDF 压缩。",
      description: "为邮件、门户和办公交付减小文件体积，同时保持下一步文档操作可见。",
      primaryCta: "上传 PDF",
      secondaryCta: "PDF 对话",
      uploadTitle: "上传 PDF 进行压缩",
      uploadDescription: "拖放 PDF 或从设备中选择文件。界面会保持限制、状态和输出预期可见。",
      formats: "PDF",
      limit: "最高 25 MB",
      cta: "选择 PDF",
      outputEyebrow: "输出",
      outputHeading: "压缩结果应该可审阅，而不只是可下载。",
      outputDescription: "结果区域建立统一的 DockDocs 模式，用于文件节省、质量检查和下一步 AI 文档操作。",
      runtimeUploadTitle: "已绑定运行状态的压缩上传",
      runtimeUploadDescription: "选择 PDF 以验证上传、已选择、处理、成功和错误状态，不改变压缩运行逻辑。",
      resultEyebrow: "压缩 PDF",
      resultTitle: "可用于办公交付",
      resultSummary: "界面已绑定所选文件状态，并只在本地运行状态成功后展示压缩输出。",
      keyPoints: ["文件更小，适合上传门户。", "文档可读性仍是主要质量信号。", "后续 AI 操作靠近结果展示。"],
      actions: ["下载压缩 PDF", "发送到 PDF 对话", "继续运行 AI 摘要"],
      emptyMessage: "请选择 PDF 以生成压缩结果预览。",
      faqTitle: "PDF 压缩常见问题",
      faqs: [
        { question: "DockDocs PDF 压缩是什么？", answer: "DockDocs PDF 压缩是 AI 文档平台工作流中的文件体积优化能力。" },
        { question: "支持哪些文件？", answer: "该界面聚焦 PDF 上传和 PDF 输出，并明确展示限制和处理状态。" },
        { question: "压缩后可以继续处理吗？", answer: "可以。结果区域会引导用户下载、复制或进入后续文档工作流。" },
        { question: "移动端可用吗？", answer: "可用。上传区域、限制和输出预览会在移动端堆叠为单列布局。" },
      ],
    },
    pdfToWord: {
      eyebrow: "转换",
      title: "将 PDF 转为可编辑的 Word 文档。",
      description: "在同一个 AI 文档平台中完成转换，并保留上传限制、输出状态和下一步操作。",
      uploadTitle: "上传 PDF 进行转换",
      uploadDescription: "拖放 PDF，准备 Word 转换工作流，不改变后端 provider 逻辑。",
      formats: "PDF",
      limit: "最高 25 MB",
      cta: "选择 PDF",
      outputEyebrow: "输出",
      outputHeading: "转换输出应该说明发生了什么。",
      outputDescription: "界面会说明可编辑内容、版式复核和后续文档操作的预期。",
      runtimeUploadTitle: "已绑定运行状态的转换上传",
      runtimeUploadDescription: "选择 PDF 以验证转换上传、处理、成功和错误状态，不改变 provider 逻辑。",
      resultEyebrow: "Word 输出",
      resultTitle: "可编辑文档已就绪",
      resultSummary: "转换后的文档已可审阅，版式说明和后续操作会显示在结果旁边。",
      keyPoints: ["文字内容已准备为可编辑状态。", "交付前仍需保留版式复核。", "用户可继续进入摘要或对话工作流。"],
      actions: ["下载 DOCX", "复核版式说明", "运行 AI 摘要"],
      emptyMessage: "请选择 PDF 以生成 Word 输出预览。",
    },
    dashboard: {
      eyebrow: "控制台",
      title: "文档工作区概览。",
      description: "用于查看最近文件、AI 活动和下一步文档操作的 SaaS 风格首页。",
      newDocument: "新建文档",
      workspace: "工作区",
      nav: ["文档", "AI", "转换", "优化", "设置"],
      stats: [
        { label: "文档", value: "18" },
        { label: "AI 运行", value: "42" },
        { label: "导出", value: "11" },
      ],
      recentLabel: "最近文档",
      continueWork: "继续处理",
      openChat: "打开 AI 对话",
      documents: [
        { name: "董事会报告.pdf", status: "已就绪", action: "AI 摘要" },
        { name: "供应商合同.pdf", status: "待复核", action: "对话" },
        { name: "扫描发票.pdf", status: "处理中", action: "OCR" },
      ],
    },
  },
} as const;

export function getRuntimeCopy(locale: RuntimeLocale = defaultLocale) {
  return runtimeCopy[locale];
}
