// Auto-generated by apps/dockdocs/scripts/generate-mission-control-data.mjs.
// Do not add secrets, local paths, or raw command logs to this file.

export const missionControlGeneratedData = {
  "generatedAt": "2026-06-04T12:59:13.705Z",
  "source": "build-time",
  "projectBoard": {
    "syncStatus": "PMO同步正常",
    "activeTasks": [
      "None"
    ],
    "blockedTasks": [
      "None confirmed"
    ],
    "completedTasks": [
      "DEV-100 (DEV)",
      "DEV-200 (DEV)",
      "DEV-300 AI Workspace Premium Phase 1 (DEV)",
      "DEV-301 Production Pro Session QA (DEV)",
      "OPS-010 (OPS)",
      "OPS-011 (OPS)",
      "OPS-100 Mission Control Phase 1 (OPS)",
      "OPS-102 Codex Task Queue Runner (OPS)",
      "OPS-102A Hardened Task Queue Runner (OPS)",
      "OPS-103 Mission Control x Task Queue (OPS)",
      "OPS-104A Project Inventory (OPS)"
    ],
    "productionStatus": [
      "Mission Control: Deployed to production",
      "Production URL: https://dockdocs.app/internal/mission-control/",
      "Latest production deploy includes: OPS-100, OPS-102, OPS-102A, OPS-103, OPS-104A, DEV-300",
      "PMO Direction: Keep Mission Control as single source of truth."
    ],
    "nextRecommended": [
      "Keep Mission Control as the single source of truth.",
      "Start the next PMO-approved production task."
    ]
  },
  "git": {
    "currentBranch": "p0s-mission-control-data-accuracy",
    "latestCommit": "a25ff86 HERMES-004: merge runner integration into master",
    "latestMasterCommits": [
      "a25ff86 HERMES-004: merge runner integration into master",
      "4a0b78e HERMES-002C: merge dispatcher queue summary into master",
      "0ffab6c HERMES-004: add runner integration",
      "7825b20 HERMES-002C: add dispatcher queue summary",
      "0f8de09 HERMES-002B: merge dispatcher queue writer into master"
    ],
    "workingTreeStatus": "dirty",
    "changedFileCount": 4
  },
  "queue": {
    "source": "PMO generated",
    "generatedAt": "2026-06-04T07:27:22.406Z",
    "pending": 0,
    "running": 0,
    "completed": 2,
    "failed": 0,
    "skipped": 0,
    "generatedTaskCount": 2,
    "pendingGeneratedTasks": [],
    "sampleTasks": [
      {
        "id": "PMO-VERIFY-001",
        "title": "Verify Keep Mission Control as the single source of truth.",
        "status": "completed"
      },
      {
        "id": "PMO-VERIFY-002",
        "title": "Verify Start the next PMO-approved production task.",
        "status": "completed"
      }
    ]
  },
  "dispatcherQueue": {
    "source": "HERMES-002B Dispatcher Queue Writer",
    "mode": "verification-only",
    "generatedAt": "2026-06-04T12:59:13.351Z",
    "summary": {
      "taskCount": 11,
      "pending": 7,
      "blocked": 0,
      "skipped": 4,
      "running": 0,
      "completed": 0,
      "failed": 0
    },
    "owners": [
      {
        "owner": "Hermes PMO",
        "count": 8
      },
      {
        "owner": "Hermes UI / Codex UI",
        "count": 1
      },
      {
        "owner": "Codex OPS",
        "count": 1
      },
      {
        "owner": "Hermes PMO / Codex OPS",
        "count": 1
      }
    ],
    "safety": {
      "merge": false,
      "push": false,
      "deploy": false,
      "destructive": false
    },
    "tasksPreview": [
      {
        "id": "DISPATCH-RISK-1",
        "title": "npm install reports 2 moderate audit issues; no audit fix was run.",
        "owner": "Hermes PMO",
        "priority": "P2",
        "status": "pending"
      },
      {
        "id": "DISPATCH-RISK-2",
        "title": "The original Dock directory should not be used for deploy if dirty.",
        "owner": "Hermes PMO",
        "priority": "P1",
        "status": "pending"
      },
      {
        "id": "DISPATCH-RISK-3",
        "title": "ai-chat is configured at /api/ai-chat, not at /.netlify/functions/ai-chat.",
        "owner": "Hermes PMO",
        "priority": "P2",
        "status": "pending"
      },
      {
        "id": "DISPATCH-RISK-4",
        "title": "ai-chat returns provider as configured-ai-provider; model confirms deepseek-chat.",
        "owner": "Hermes PMO",
        "priority": "P1",
        "status": "pending"
      },
      {
        "id": "DISPATCH-RISK-5",
        "title": "UI-301A is missing from the PMO board; using current release fallback.",
        "owner": "Hermes UI / Codex UI",
        "priority": "P2",
        "status": "pending"
      }
    ]
  },
  "runnerSummary": {
    "source": "HERMES-004 Runner Integration",
    "mode": "verification-only",
    "safetyMode": "Enabled",
    "taskCount": 11,
    "completed": 7,
    "failed": 0,
    "skipped": 4,
    "lastRun": "2026-06-04T12:45:13.297Z",
    "executionDurationMs": 16242,
    "safety": {
      "merge": false,
      "push": false,
      "deploy": false,
      "destructive": false
    }
  },
  "productionEvidence": {
    "source": "OPS-117 production monitoring snapshot",
    "deployId": "6a21623690964f2393f2ed06",
    "latestMaster": {
      "commit": "873fef9",
      "message": "UI-DS-03: merge unified status badge system into master"
    },
    "productionUrl": "https://dockdocs.app",
    "productionQaPassed": true,
    "included": [
      "UI-DS-03",
      "HERMES-002A",
      "OPS-111",
      "OPS-113"
    ]
  },
  "inventory": {
    "tasks": [
      {
        "id": "DEV-100",
        "label": "Commercialization MVP",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-200",
        "label": "Billing MVP",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-300",
        "label": "AI Workspace Premium Phase 1",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-301",
        "label": "Production Pro Session QA",
        "area": "DEV",
        "status": "Completed"
      },
      {
        "id": "UI-301A",
        "label": "中文内部项目驾驶舱",
        "area": "UI",
        "status": "Completed"
      },
      {
        "id": "OPS-010",
        "label": "Google OAuth enablement follow-up",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-011",
        "label": "Production login validation follow-up",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-100",
        "label": "Mission Control Phase 1",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-102",
        "label": "Codex Task Queue Runner",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-102A",
        "label": "Hardened Task Queue Runner",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-103",
        "label": "Mission Control x Task Queue",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-104A",
        "label": "Project Inventory",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-106",
        "label": "Mission Control Auto Sync",
        "area": "OPS",
        "status": "Completed"
      },
      {
        "id": "UI-302",
        "label": "Mission Control Owner Dashboard",
        "area": "UI",
        "status": "Production",
        "detail": "OPS-117 production monitoring confirms UI-302 was merged, deployed, and production QA passed."
      },
      {
        "id": "UI-DS-03",
        "label": "Unified Status Badge System",
        "area": "UI",
        "status": "Production",
        "detail": "OPS-117 production monitoring confirms UI-DS-03 was merged, deployed, and production QA passed."
      },
      {
        "id": "HERMES-002A",
        "label": "Dispatcher Data Model",
        "area": "HERMES",
        "status": "Production",
        "detail": "Dispatcher Summary is present in the OPS-117 production monitoring snapshot."
      },
      {
        "id": "HERMES-001A",
        "label": "Observer Report Generator",
        "area": "HERMES",
        "status": "Production",
        "detail": "Observer Report Summary is present in the production Mission Control baseline."
      },
      {
        "id": "HERMES-002B",
        "label": "Dispatcher Queue Writer",
        "area": "HERMES",
        "status": "Completed",
        "detail": "Dispatcher queue writer is merged and generates verification-only dispatch queue data."
      },
      {
        "id": "OPS-108",
        "label": "Task Queue Writer",
        "area": "OPS",
        "status": "Production",
        "detail": "PMO to task queue writer is present in the current automation baseline."
      },
      {
        "id": "OPS-110",
        "label": "Auto Pickup Stability",
        "area": "OPS",
        "status": "Production",
        "detail": "Auto pickup stability fixes are present in the current automation baseline."
      },
      {
        "id": "OPS-111",
        "label": "Watch Mode",
        "area": "OPS",
        "status": "Production",
        "detail": "OPS-117 production monitoring snapshot includes OPS-111 Watch Mode."
      },
      {
        "id": "OPS-113",
        "label": "Production Monitoring Baseline",
        "area": "OPS",
        "status": "Production",
        "detail": "OPS-117 production monitoring snapshot includes OPS-113 Monitoring Baseline."
      },
      {
        "id": "OPS-117",
        "label": "Production Monitoring Snapshot",
        "area": "OPS",
        "status": "Production",
        "detail": "OPS-117 production monitoring snapshot is the latest deploy evidence source."
      }
    ],
    "branches": [
      {
        "id": "master",
        "label": "Production branch",
        "status": "Active"
      },
      {
        "id": "ops-106-mission-control-auto-sync",
        "label": "OPS-106 build-time auto sync",
        "status": "Completed"
      }
    ],
    "prs": [
      {
        "id": "OPS-100",
        "label": "Mission Control Phase 1",
        "status": "Merged"
      },
      {
        "id": "OPS-102",
        "label": "Task Queue Runner",
        "status": "Merged"
      },
      {
        "id": "OPS-103",
        "label": "Mission Control x Task Queue",
        "status": "Merged"
      },
      {
        "id": "OPS-104A",
        "label": "Project Inventory",
        "status": "Merged"
      },
      {
        "id": "DEV-300",
        "label": "AI Workspace Premium",
        "status": "Production"
      },
      {
        "id": "DEV-301",
        "label": "Production Pro Session QA",
        "status": "Completed"
      },
      {
        "id": "UI-301A",
        "label": "Chinese Mission Control",
        "status": "Completed"
      },
      {
        "id": "OPS-106",
        "label": "Mission Control Auto Sync",
        "status": "Completed"
      }
    ],
    "agents": [
      {
        "id": "GPT",
        "label": "Strategy / product direction",
        "status": "Active"
      },
      {
        "id": "Hermes PMO",
        "label": "Project board / task state",
        "status": "Active"
      },
      {
        "id": "Hermes DEV",
        "label": "Engineering coordination",
        "status": "Active"
      },
      {
        "id": "Hermes UI",
        "label": "UX acceptance criteria",
        "status": "Active"
      },
      {
        "id": "Codex OPS",
        "label": "Infrastructure execution",
        "status": "Active"
      },
      {
        "id": "Codex DEV",
        "label": "Product implementation",
        "status": "Active"
      }
    ]
  },
  "warnings": [
    "UI-301A is missing from the PMO board; using current release fallback.",
    "OPS-106 is missing from the PMO board; using current release fallback."
  ]
} as const;
