// Auto-generated by apps/dockdocs/scripts/generate-mission-control-data.mjs.
// Do not add secrets, local paths, or raw command logs to this file.

export const missionControlGeneratedData = {
  "generatedAt": "2026-06-04T07:02:44.379Z",
  "source": "build-time",
  "projectBoard": {
    "syncStatus": "PMO同步正常",
    "activeTasks": [
      "None"
    ],
    "blockedTasks": [
      "None confirmed"
    ],
    "completedTasks": [
      "DEV-100 (DEV)",
      "DEV-200 (DEV)",
      "DEV-300 AI Workspace Premium Phase 1 (DEV)",
      "DEV-301 Production Pro Session QA (DEV)",
      "OPS-010 (OPS)",
      "OPS-011 (OPS)",
      "OPS-100 Mission Control Phase 1 (OPS)",
      "OPS-102 Codex Task Queue Runner (OPS)",
      "OPS-102A Hardened Task Queue Runner (OPS)",
      "OPS-103 Mission Control x Task Queue (OPS)",
      "OPS-104A Project Inventory (OPS)"
    ],
    "productionStatus": [
      "Mission Control: Deployed to production",
      "Production URL: https://dockdocs.app/internal/mission-control/",
      "Latest production deploy includes: OPS-100, OPS-102, OPS-102A, OPS-103, OPS-104A, DEV-300",
      "PMO Direction: Keep Mission Control as single source of truth."
    ],
    "nextRecommended": [
      "Keep Mission Control as the single source of truth.",
      "Start the next PMO-approved production task."
    ]
  },
  "git": {
    "currentBranch": "ops-110-auto-pickup-stability",
    "latestCommit": "7d4f320 OPS-108: merge Codex task queue writer into master",
    "latestMasterCommits": [
      "7d4f320 OPS-108: merge Codex task queue writer into master",
      "764627b OPS-108: generate Codex task queue from PMO board",
      "7dfc4aa OPS-107: merge PMO Sync into master",
      "7c184a9 OPS-107: sync Mission Control from PMO board",
      "21460aa UI-301A: merge Chinese Mission Control into master"
    ],
    "workingTreeStatus": "dirty",
    "changedFileCount": 11
  },
  "queue": {
    "source": "PMO generated",
    "generatedAt": "2026-06-04T07:01:14.301Z",
    "pending": 0,
    "running": 0,
    "completed": 2,
    "failed": 0,
    "skipped": 0,
    "generatedTaskCount": 2,
    "pendingGeneratedTasks": [],
    "sampleTasks": [
      {
        "id": "PMO-VERIFY-001",
        "title": "Verify Keep Mission Control as the single source of truth.",
        "status": "completed"
      },
      {
        "id": "PMO-VERIFY-002",
        "title": "Verify Start the next PMO-approved production task.",
        "status": "completed"
      }
    ]
  },
  "inventory": {
    "tasks": [
      {
        "id": "DEV-100",
        "label": "Commercialization MVP",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-200",
        "label": "Billing MVP",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-300",
        "label": "AI Workspace Premium Phase 1",
        "area": "DEV",
        "status": "Production"
      },
      {
        "id": "DEV-301",
        "label": "Production Pro Session QA",
        "area": "DEV",
        "status": "Completed"
      },
      {
        "id": "UI-301A",
        "label": "中文内部项目驾驶舱",
        "area": "UI",
        "status": "Completed"
      },
      {
        "id": "OPS-010",
        "label": "Google OAuth enablement follow-up",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-011",
        "label": "Production login validation follow-up",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-100",
        "label": "Mission Control Phase 1",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-102",
        "label": "Codex Task Queue Runner",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-102A",
        "label": "Hardened Task Queue Runner",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-103",
        "label": "Mission Control x Task Queue",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-104A",
        "label": "Project Inventory",
        "area": "OPS",
        "status": "Production"
      },
      {
        "id": "OPS-106",
        "label": "Mission Control Auto Sync",
        "area": "OPS",
        "status": "Completed"
      }
    ],
    "branches": [
      {
        "id": "master",
        "label": "Production branch",
        "status": "Active"
      },
      {
        "id": "ops-106-mission-control-auto-sync",
        "label": "OPS-106 build-time auto sync",
        "status": "Completed"
      }
    ],
    "prs": [
      {
        "id": "OPS-100",
        "label": "Mission Control Phase 1",
        "status": "Merged"
      },
      {
        "id": "OPS-102",
        "label": "Task Queue Runner",
        "status": "Merged"
      },
      {
        "id": "OPS-103",
        "label": "Mission Control x Task Queue",
        "status": "Merged"
      },
      {
        "id": "OPS-104A",
        "label": "Project Inventory",
        "status": "Merged"
      },
      {
        "id": "DEV-300",
        "label": "AI Workspace Premium",
        "status": "Production"
      },
      {
        "id": "DEV-301",
        "label": "Production Pro Session QA",
        "status": "Completed"
      },
      {
        "id": "UI-301A",
        "label": "Chinese Mission Control",
        "status": "Completed"
      },
      {
        "id": "OPS-106",
        "label": "Mission Control Auto Sync",
        "status": "Completed"
      }
    ],
    "agents": [
      {
        "id": "GPT",
        "label": "Strategy / product direction",
        "status": "Active"
      },
      {
        "id": "Hermes PMO",
        "label": "Project board / task state",
        "status": "Active"
      },
      {
        "id": "Hermes DEV",
        "label": "Engineering coordination",
        "status": "Active"
      },
      {
        "id": "Hermes UI",
        "label": "UX acceptance criteria",
        "status": "Active"
      },
      {
        "id": "Codex OPS",
        "label": "Infrastructure execution",
        "status": "Active"
      },
      {
        "id": "Codex DEV",
        "label": "Product implementation",
        "status": "Active"
      }
    ]
  },
  "warnings": [
    "UI-301A is missing from the PMO board; using current release fallback.",
    "OPS-106 is missing from the PMO board; using current release fallback."
  ]
} as const;
